version = 1

[[annotations]]
path = [
    "TODO",
    "README.md",
    ".gitignore",
    "doc/**"
]
SPDX-FileCopyrightText  = "Copyright (C) 2026 Mark H. (aka maki73)"
SPDX-License-Identifier = "LGPL-2.1-or-later" # TODO: or make it CC-BY-4.0?
