# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2026 Mark H. (aka maki73)
#
# This file is part of FineSword Math Library Testing Infrastructure.
# See COPYING and COPYING.LESSER for the full license text.
#
name: FineSword CI (Native)

# on:
#   push:
#     # branches:
#     #   - main

# TODO:
