# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2026 Mark H. (aka maki73)
#
# This file is part of FineSword Math Library Testing Infrastructure.
# See COPYING and COPYING.LESSER for the full license text.
#

name: FineSword CI (Linting)

on:
  push:
    # branches:
    #   - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install Python 3
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"

    - name: Install Cppcheck
      run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
    
    - name: Install REUSE (through pip)
      run: |
          python -m pip install "reuse[charset-normalized]==6.2.0" 

    - name: Lint
      run: |
        echo "[~] ./auxiliary/newline.py..."
        python auxiliary/newline.py src/ tests/ include/ auxiliary/ CMakeLists.txt

        echo "[~] ./auxiliary/guard.py..."
        python auxiliary/guard.py
        
        echo "[~] ./auxiliary/license.py..."
        python auxiliary/license.py
        
        echo "[~] ./auxiliary/rules.sh..."
        ./auxiliary/rules.sh
