# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2026 Mark H. (aka maki73)
#
# This file is part of FineSword Math Library Testing Infrastructure.
# See COPYING and COPYING.LESSER for the full license text.
#

name: FineSword CI (Native)

on:
  push:
    # branches:
    #   - main

jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: true
      matrix:
        include:
          # --- x86 --- 

          # Linux GCC
          - os: Linux x86-64
            runner: ubuntu-latest
            compiler: GCC
            cc: gcc

          # Linux Clang
          - os: Linux x86-64
            runner: ubuntu-latest
            compiler: Clang
            cc: clang

          # Windows MSVC
          - os: Windows x86-64
            runner: windows-latest
            compiler: MSVC
            cc: cl
          
          # Linux ICX
          - os: Linux x86-64
            runner: ubuntu-latest
            compiler: ICX
            cc: icx
          
          # Linux TinyCC (build only)
          - os: Linux x86-64
            runner: ubuntu-latest
            compiler: TinyCC
            cc: tcc

          # --- ARM ---

          # Linux GCC
          - os: Linux AArch64
            runner: ubuntu-24.04-arm
            compiler: GCC
            cc: gcc

          # Linux Clang
          - os: Linux AArch64
            runner: ubuntu-24.04-arm
            compiler: Clang
            cc: clang

          # macOS AppleClang
          - os: macOS arm64
            runner: macos-latest
            compiler: Clang
            cc: clang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: if Linux apt-get install Clang & OpenMP
        if:  runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libomp-dev libgomp1
      
      - name: if macOS brew install OMP 
        if:  runner.os == 'macOS'
        run: |
          brew update
          brew install libomp
      
      - name: if macOS fix set OpenMP envvars
        if: runner.os == 'macOS'
        run: |
          OMP_PREFIX="$(brew --prefix libomp)"
          {
            echo "OpenMP_ROOT=${OMP_PREFIX}"
            echo "CMAKE_PREFIX_PATH=${OMP_PREFIX}:${CMAKE_PREFIX_PATH}"
            echo "LDFLAGS=-L${OMP_PREFIX}/lib ${LDFLAGS}"
          } >> "$GITHUB_ENV"

      - name: if Linux/ICX install ICX
        if:  matrix.compiler == 'ICX'
        run: |
          sudo apt-get install -y gpg-agent wget
          
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
            | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp

          source /opt/intel/oneapi/setvars.sh
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
          echo "LIBRARY_PATH=${LIBRARY_PATH:-}"       >> "$GITHUB_ENV"
          echo "$(dirname "$(command -v icx)")"       >> "$GITHUB_PATH"
          
          echo "icx: $(command -v icx)" # diagnostics
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

      - name: if Linux/TinyCC apt-get install tcc & set CC=tcc
        if: matrix.compiler == 'TinyCC'
        run: |
          sudo apt-get install -y tcc
          echo "CC=tcc" >> "$GITHUB_ENV"


      - name: Configure CMake
        shell: bash
        env:
          CC: ${{ matrix.cc }}
        run: cmake . -B build -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Release
        
      - name: CMake Build
        run: cmake --build build --config Release

      - name: Test All Exhaustive
        if: matrix.compiler != 'TinyCC'
        run: |
          python auxiliary/comprehensive_self.py
          python auxiliary/functions_extern.py
